// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using travel2gether.Data;

namespace travel2gether.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210420142743_jpg-textEnin")]
    partial class jpgtextEnin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("travel2gether.Models.DomesticOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailsSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DomesticOffers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 30000,
                            Destination = "Salgótarján",
                            DetailsSrc = "\\assets\\domestic\\txt\\1.txt",
                            EndTime = "2021.06.22",
                            PicSrc = "\\assets\\domestic\\img\\1.jpg",
                            ShortDescription = "Kicsiny csoda fenn északon",
                            StartTime = "2021.06.20"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 10000,
                            Destination = "Hévíz",
                            DetailsSrc = "\\assets\\domestic\\txt\\2.txt",
                            EndTime = "2021.07.19",
                            PicSrc = "\\assets\\domestic\\img\\2.jpg",
                            ShortDescription = "Az idő nem kifogás, itt mindenhogy csodás",
                            StartTime = "2021.07.11"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 30000,
                            Destination = "Eger",
                            DetailsSrc = "\\assets\\domestic\\txt\\3.txt",
                            EndTime = "2021.06.22",
                            PicSrc = "\\assets\\domestic\\img\\3.jpg",
                            ShortDescription = "Vissza a múltba",
                            StartTime = "2021.09.20"
                        });
                });

            modelBuilder.Entity("travel2gether.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hashtag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicSrc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "\\assets\\news\\body\\1.txt",
                            Date = "2021.04.10",
                            Hashtag = " karanten",
                            Header = "Belgium nyitásra kész!",
                            PicSrc = "\\assets\\news\\img\\1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Body = "\\assets\\news\\body\\2.txt",
                            Date = "2021.03.21",
                            Hashtag = "2021nyar",
                            Header = "Még most érdemes foglalni nyárra",
                            PicSrc = "\\assets\\news\\img\\2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Body = "\\assets\\news\\body\\3.txt",
                            Date = "2021.04.05",
                            Hashtag = "FociVB",
                            Header = "Kicsiny hazánk teljes mértékben támogatja a foci vb-t ",
                            PicSrc = "\\assets\\news\\img\\3.jpg"
                        });
                });

            modelBuilder.Entity("travel2gether.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Continent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailsSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Continent = "Europa",
                            Cost = 120000,
                            Destination = "Barcelona",
                            DetailsSrc = "\\assets\\txt\\Barcelona.txt",
                            EndTime = "2021.06.18",
                            PicSrc = "\\assets\\img\\Barcelona.jpg",
                            ShortDescription = "Spanyolr riviéra!",
                            StartTime = "2021.06.12"
                        },
                        new
                        {
                            Id = 2,
                            Continent = "Europa",
                            Cost = 80000,
                            Destination = "Oslo",
                            DetailsSrc = "\\assets\\txt\\Oslo.txt ",
                            EndTime = "2021.11.07",
                            PicSrc = "\\assets\\img\\Oslo.jpg",
                            ShortDescription = "Lelket melengető pihenés",
                            StartTime = "2021.11.01"
                        },
                        new
                        {
                            Id = 3,
                            Continent = "Europa",
                            Cost = 90000,
                            Destination = "Edinburgh",
                            DetailsSrc = "\\assets\\txt\\Edinburgh.txt ",
                            EndTime = "2021.08.25",
                            PicSrc = "\\assets\\img\\Edinburgh.jpg",
                            ShortDescription = "Attól, mert az idő szomorkás, neked nem kell annak lenni!",
                            StartTime = "2021.08.20"
                        });
                });

            modelBuilder.Entity("travel2gether.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
